<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDataRepository extends EntityRepository
{
    const FIELD_NAME_PRODUCT_DATA_ID = 'productDataId';
    const FIELD_NAME_PRODUCT_NAME    = 'productName';
    const FIELD_NAME_PRODUCT_DESC    = 'productDesc';
    const FIELD_NAME_PRODUCT_CODE    = 'productCode';
    const FIELD_NAME_STOCK           = 'stock';
    const FIELD_NAME_COST            = 'cost';
    const FIELD_NAME_ADDED           = 'added';
    const FIELD_NAME_DISCONTINUED    = 'discontinued';
}
